# -*- coding: utf-8 -*-
"""Bulk Exception Dismiss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUQusJP-gR-J10SRxaqWhotR2nEH67qi

Initial Library downloads Config
"""

!pip install mygeotab

"""MAIN Function Exception Bulk dismiss"""

import mygeotab
import datetime

# @title Geotab Exception Dismissal Tool
# @markdown Fill in your credentials and search criteria.

print("--- Geotab Exception Dismissal Tool ---")
USERNAME = input("Enter Geotab Username: ")
PASSWORD = input("Enter Geotab Password: ")
DATABASE = input("Enter Database Name: ")
DEVICE_ID = input("Enter Device ID: ")
RULE_NAME = input("Enter Rule Name to dismiss: ")
START_DATE = input("Enter Start Date (YYYY-MM-DD): ")

def main():
    client = mygeotab.API(username=USERNAME, password=PASSWORD, database=DATABASE, server=SERVER)
    try:
        client.authenticate()
    except Exception as e:
        print(f"Authentication failed: {e}")
        return

    # 1. Get the Rule ID based on the name provided
    rules = client.call("Get", typeName="Rule", search={"name": RULE_NAME})
    if not rules:
        print(f"No rule found with name: {RULE_NAME}")
        return
    rule_id = rules[0]['id']

    # 2. Setup the dates (Baseline uses a 24-hour window)
    from_date = datetime.datetime.strptime(START_DATE, "%Y-%m-%d")
    to_date = from_date + datetime.timedelta(days=1)

    print(f"Searching for exceptions for Device {DEVICE_ID} and Rule {RULE_NAME}...")

    # 3. Get Exception Events
    exceptions = client.call("Get", typeName="ExceptionEvent", search={
        "fromDate": from_date.isoformat(),
        "toDate": to_date.isoformat(),
        "deviceSearch": {"id": DEVICE_ID},
        "ruleSearch": {"id": rule_id}
    })

    if not exceptions:
        print("No exceptions found matching those criteria.")
        return

    print(f"Found {len(exceptions)} exceptions. Starting dismissal...")

    # 4. Dismiss via MultiCall (Batch processing is faster and safer for API limits)
    # We only dismiss exceptions that aren't already dismissed.
    calls = []
    for ex in exceptions:
        if ex.get("state") != "ExceptionEventStateDismissedId":
            calls.append([
                "Set",
                {
                    "typeName": "ExceptionEvent",
                    "entity": {
                        "id": ex["id"],
                        "state": "ExceptionEventStateDismissedId"
                    }
                }
            ])

    # Execute in batches of 100 to avoid timeout
    if calls:
        batch_size = 100
        for i in range(0, len(calls), batch_size):
            batch = calls[i:i + batch_size]
            client.multi_call(batch)
            print(f"Dismissed {i + len(batch)} / {len(calls)}...")

        print("Done! All targeted exceptions have been dismissed.")
    else:
        print("All found exceptions were already dismissed.")

if __name__ == "__main__":
    main()